import React from "react";
import Stripe from "@/components/Stripe";
import Head from "next/head";

function StripePage() {
  return (
    <>
      <Head>
        <title>Buy Cryptocurrency | SubsCrypt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stripe />
    </>
  );
}

export default StripePage;
